[package]
name = "datafusion-functions-json"
version = "0.47.0"
edition = "2021"
description = "JSON functions for DataFusion"
readme = "README.md"
license = "Apache-2.0"
keywords = ["datafusion", "JSON", "SQL"]
categories = ["database-implementations", "parsing"]
repository = "https://github.com/datafusion-contrib/datafusion-functions-json/"
rust-version = "1.82.0"

[dependencies]
datafusion = { git = "https://github.com/allinux/datafusion.git", rev = "1a24d29bb992f8b71c3fdceb45208707d172d0af", default-features = false }
jiter = { git = "https://github.com/allinux/jiter.git", rev = "5f6e6732a3b27d6e5197d2965638b2e5ce09a6de" }
paste = "1"
log = "0.4"

[dev-dependencies]
datafusion = { git = "https://github.com/allinux/datafusion.git", rev = "1a24d29bb992f8b71c3fdceb45208707d172d0af", default-features = false, features = ["nested_expressions"] }
codspeed-criterion-compat = "2.6"
criterion = "0.5.1"
clap = "4"
tokio = { version = "1.43", features = ["full"] }

[lints.clippy]
dbg_macro = "deny"
print_stdout = "deny"

# in general, we lint against the pedantic group, but we will whitelist
# certain lints which we don't want to enforce (for now)
pedantic = { level = "deny", priority = -1 }

[[bench]]
name = "main"
harness = false
